#!/bin/bash
# lli out.bc
# ./dist-newstyle/compiler "$1" 

DIRNAME=`dirname $1`
BASENAME=`basename $1 .lat`
LLVM="$DIRNAME/${BASENAME}.ll"
LLVMBC="$DIRNAME/${BASENAME}.bc"
./dist-newstyle/compiler "$1" > $LLVM
llvm-as $LLVM -o $LLVMBC
llvm-link -o $LLVMBC $LLVMBC lib/runtime.bc